spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  default-number-of-retries: 10
  history-level: full
  admin-user:
    id: demo
    password: demo
  filter:
    create: All tasks
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.dmn
    - classpath*:**/*.form